name: Publish NuGet Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Serilog.Sinks.NetMail/Serilog.Sinks.NetMail.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/Serilog.Sinks.NetMail/Serilog.Sinks.NetMail.csproj

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkg src/Serilog.Sinks.NetMail/Serilog.Sinks.NetMail.csproj

      - name: Publish NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
